### ISSUE TITLE
Incomplete Translation of subscription form

### ISSUE THREAD

**Issue by marcorensch** [rvalitov/widgetkit-map-ex#38]
### Expected behavior

All Text Phrases are in the selected Language
### Actual behavior

For at least one Text Phrase is no translation avaiable.
### Steps to reproduce the behavior

Do A Subscription for the Newsletter - tafter the click on submit his text appears:
"Almost finished... We need to confirm your email address. To complete the subscription process, please click the link in the email we just sent you."
### System information

**CMS type**: Joomla

**CMS version**: 3.5.1

**Version of the widget**: 1.5.0.2

**Website URL**: inst.nx-designs.ch

**Debug output of the widget**:
still on :-)

**Comment by rvalitov** [comment]
Thank you for reporting this! Some strings (for example the one you mentioned here) in the widget are generated by third party plugins or services. So, such strings are not included into the translation files. For the strings you mentioned I think it's possible to translate the text, because the service used for subscription is multilingual. I will check it.

**Comment by rvalitov** [comment]
Fixed
