### ISSUE TITLE
Google API Key will not work

### ISSUE THREAD

**Issue by sveneick** [rvalitov/widgetkit-map-ex#51]
Hello,

It seems as if the API key is not being used properly. If I use the normal map widget, I have no problems. When I use the Map-Ex widget, I get an error message. Both widgets use the same API key. See: http://www.geliti.de/urlaub-am-petzinsee/ausflugsziele

That worked until recently. This must have happened with an update. I am using J3.6.4 and Widgetkit 2.8.0.

Can you help me?

Thanks, Sven

**Comment by rvalitov** [comment]
Hello, thank you for reporting this. I didn't test this widget with the latest WK yet. I will do it soon and give you the response.

**Comment by rvalitov** [comment]
Hi Sven,
I updated to the latest Joomla and Widgetkit. Everything works fine on my hosting. I used the API key only in the settings of the MapEx widget. It seems that this error is local and is related to your hosting or settings of the widget. 

Can you please give me the access to the Joomla backend, so that I can check your settings? You can send me the login/password privately to this e-mail: ramilvalitov@gmail.com

**Comment by rvalitov** [comment]
Checked your hosting. You installed the widget in the wrong directory. Please, remove it. And then install correctly using the following manual https://github.com/rvalitov/widgetkit-map-ex/wiki/How-to-install

**Comment by sveneick** [comment]
That was it, wrong directory! Now everything works again. Thank you for your help.
