### ISSUE TITLE
Need some help; end of page

### ISSUE THREAD

**Issue by SylaSyla** [rvalitov/widgetkit-map-ex#68]
First of all, love all the extra options of the widgekit map ex  👍 

As soon as i enable a module (content-top position) with the widgekit Map ex the end of the page is gone...
Like the became page longer (sorry don't know how to discripe it )
![afbeelding](https://cloud.githubusercontent.com/assets/27548522/25062302/4e84346a-21ca-11e7-8075-50468c8fa26d.png)

When I disable the module the end of the page/site is back to normal
When I use the Zoo widgekit Map the end of the page is normal as well.

Please advice

**Comment by rvalitov** [comment]
Hi! Can you please post a link to your website, where I can see this problem?

**Comment by SylaSyla** [comment]
Hi, 
please see following:
http://testsite.024nijmegen.nl/www/category/benedenstad   (widgekit mapex)
http://testsite.024nijmegen.nl/www/category/stadscentrum    (widgetkit standart map)

**Comment by rvalitov** [comment]
Thank you for the links. I checked it. This problem is not caused by the MapEx widget. The code inspector reveals that the problem is caused by two `<div>` tags with class `"ial-window"`:
![image](https://cloud.githubusercontent.com/assets/16267156/25135951/60121c3a-245c-11e7-85e9-dfe841fd75aa.png)

These divs are not generated by the widget, so you should look into the other plugins that do it. The CSS `"top"` value is set explicitly, which leads to making the height of the page bigger than expected.

**Comment by SylaSyla** [comment]
Thanks for your reply.
I tried turning JCH plugin off,
the empty space is gone but the 2 divs are still there.
I turned the login modulle off and the 2 divs are gone also with the jch plugin on
Unfortunally the developper of the ajax login module is not responding for weeks anymore :-(

**Comment by rvalitov** [comment]
Then I can mark this issue as solved. It seems the problem is related to the ajax login module. If you need any private customization of the widgets or other private programming services not related to widgetkit, you can contact me ramilvalitov@gmail.com
